name: 'Node.js License Compliance Checker'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-licenses-node:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out Code'
        uses: actions/checkout@v3

      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Install license checker'
        run: npm i license-checker

      - name: 'Run license checker'
        run: npx license-checker --csv --direct >> licenses.csv
